server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.245.129:3306/cloud_order?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice # order 服务的服务名称
  cloud:
    nacos:
      server-addr: 192.168.245.129:8848
      discovery:
        cluster-name: HZ # 集群名称
        ephemeral: false # 设置为非临时实例
#        namespace: 5c731ad5-36ac-4c46-8df2-2b34c55b1a48 # dev 环境
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url: # eureka 的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
userservice: # 给某个微服务配置负载均衡规则，这里是userservice服务
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则 默认的`ZoneAvoidanceRule`并不能实现根据同集群优先来实现负载均衡。因此 Nacos 中提供了一个 NacosRule 的实现，可以优先从同集群中挑选实例（此处是随机，而不是轮询）。
ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients:  #指定饥饿加载的服务名称
      - userservice