spring:
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.92.128:3306/mybatis_plus?characterEncoding=utf-8&userSSL=false
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #设置 mybatis-plus 的全局配置
  global-config:
    db-config:
      # 配置 MyBatis-Plus 操作表的默认前缀
      table-prefix: t_
      # 配置MyBatis-Plus的主键策略
      id-type: auto
  # 配置类型别名所对应的包
  type-aliases-package: com.lotushint.mybatisplus.pojo
  # 扫描通用枚举的包
  type-enums-package: com.lotushint.mybatisplus.enums